/**
 * <pre>
 * 
 *  Accela Citizen Access
 *  File: CapModel4WS.cs
 * 
 *  Accela, Inc.
 *  Copyright (C): 2007-2014
 * 
 *  Description:
 * 
 *  Notes:
 * $Id: Reference.cs 275790 2014-07-23 08:19:31Z ACHIEVO\james.shi $.
 *  Revision History
 *  &lt;Date&gt;,    &lt;Who&gt;,    &lt;What&gt;
 * </pre>
 */
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.1433.
// 
#pragma warning disable 1591

namespace Accela.ACA.WSProxy {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="OwnerWebServiceServiceSoapBinding", Namespace="http://service.webservice.accela.com/")]
    public partial class OwnerWebServiceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getOwnerConditionOperationCompleted;
        
        private System.Threading.SendOrPostCallback getOwnerByPKOperationCompleted;
        
        private System.Threading.SendOrPostCallback getAPOListOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public OwnerWebServiceService() {
            
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getOwnerConditionCompletedEventHandler getOwnerConditionCompleted;
        
        /// <remarks/>
        public event getOwnerByPKCompletedEventHandler getOwnerByPKCompleted;
        
        /// <remarks/>
        public event getAPOListCompletedEventHandler getAPOListCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.webservice.accela.com/", ResponseNamespace="http://service.webservice.accela.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OwnerModel getOwnerCondition([System.Xml.Serialization.XmlElementAttribute("arg0", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string[] arg0, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] OwnerModel arg1, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg2)
        {
            object[] results = this.Invoke("getOwnerCondition", new object[] {
                        arg0,
                        arg1,
                        arg2});
            return ((OwnerModel)(results[0]));
        }
        
        /// <remarks/>
        public void getOwnerConditionAsync(string[] arg0, OwnerModel arg1, string arg2) {
            this.getOwnerConditionAsync(arg0, arg1, arg2, null);
        }
        
        /// <remarks/>
        public void getOwnerConditionAsync(string[] arg0, OwnerModel arg1, string arg2, object userState)
        {
            if ((this.getOwnerConditionOperationCompleted == null)) {
                this.getOwnerConditionOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetOwnerConditionOperationCompleted);
            }
            this.InvokeAsync("getOwnerCondition", new object[] {
                        arg0,
                        arg1,
                        arg2}, this.getOwnerConditionOperationCompleted, userState);
        }
        
        private void OngetOwnerConditionOperationCompleted(object arg) {
            if ((this.getOwnerConditionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getOwnerConditionCompleted(this, new getOwnerConditionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.webservice.accela.com/", ResponseNamespace="http://service.webservice.accela.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OwnerModel getOwnerByPK([System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] OwnerModel arg1)
        {
            object[] results = this.Invoke("getOwnerByPK", new object[] {
                        arg0,
                        arg1});
            return ((OwnerModel)(results[0]));
        }
        
        /// <remarks/>
        public void getOwnerByPKAsync(string arg0, OwnerModel arg1)
        {
            this.getOwnerByPKAsync(arg0, arg1, null);
        }
        
        /// <remarks/>
        public void getOwnerByPKAsync(string arg0, OwnerModel arg1, object userState)
        {
            if ((this.getOwnerByPKOperationCompleted == null)) {
                this.getOwnerByPKOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetOwnerByPKOperationCompleted);
            }
            this.InvokeAsync("getOwnerByPK", new object[] {
                        arg0,
                        arg1}, this.getOwnerByPKOperationCompleted, userState);
        }
        
        private void OngetOwnerByPKOperationCompleted(object arg) {
            if ((this.getOwnerByPKCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getOwnerByPKCompleted(this, new getOwnerByPKCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.webservice.accela.com/", ResponseNamespace="http://service.webservice.accela.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SearchResultModel getAPOList([System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] ParcelInfoModel arg1, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] QueryFormat arg2, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] bool arg3)
        {
            object[] results = this.Invoke("getAPOList", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3});
            return ((SearchResultModel)(results[0]));
        }
        
        /// <remarks/>
        public void getAPOListAsync(string arg0, ParcelInfoModel arg1, QueryFormat arg2, bool arg3) {
            this.getAPOListAsync(arg0, arg1, arg2, arg3, null);
        }
        
        /// <remarks/>
        public void getAPOListAsync(string arg0, ParcelInfoModel arg1, QueryFormat arg2, bool arg3, object userState) {
            if ((this.getAPOListOperationCompleted == null)) {
                this.getAPOListOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAPOListOperationCompleted);
            }
            this.InvokeAsync("getAPOList", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3}, this.getAPOListOperationCompleted, userState);
        }
        
        private void OngetAPOListOperationCompleted(object arg) {
            if ((this.getAPOListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAPOListCompleted(this, new getAPOListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
 
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void getOwnerConditionCompletedEventHandler(object sender, getOwnerConditionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getOwnerConditionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getOwnerConditionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OwnerModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OwnerModel)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void getOwnerByPKCompletedEventHandler(object sender, getOwnerByPKCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getOwnerByPKCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getOwnerByPKCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OwnerModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OwnerModel)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591
