//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accela.ACA.Web.Component {
    
    
    public partial class ParcelSearchResult {
        
        /// <summary>
        /// lblParcelSession control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Accela.Web.Controls.AccelaLabel lblParcelSession;
        
        /// <summary>
        /// ucParcelList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Accela.ACA.Web.Component.RefAPOParcelList ucParcelList;
        
        /// <summary>
        /// divConditon control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divConditon;
        
        /// <summary>
        /// ucConditon control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Accela.ACA.Web.Component.Conditions ucConditon;
        
        /// <summary>
        /// divParcelAssociates control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divParcelAssociates;
        
        /// <summary>
        /// lblAddressSession control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Accela.Web.Controls.AccelaLabel lblAddressSession;
        
        /// <summary>
        /// ucAddressList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Accela.ACA.Web.Component.AddressSearchList ucAddressList;
        
        /// <summary>
        /// lblOwnerSession control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Accela.Web.Controls.AccelaLabel lblOwnerSession;
        
        /// <summary>
        /// ucOwnerList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Accela.ACA.Web.Component.RefAPOOwnerList ucOwnerList;
    }
}
