/**
 * <pre>
 * 
 *  Accela Citizen Access
 *  File: PageFlowConfigWebService.cs
 * 
 *  Accela, Inc.
 *  Copyright (C): 2007-2012
 * 
 *  Description:
 * 
 *  Notes:
 * $Id: Reference.cs 215309 2012-03-08 10:34:02Z ACHIEVO\daly.zeng $.
 *  Revision History
 *  &lt;Date&gt;,    &lt;Who&gt;,    &lt;What&gt;
 * </pre>
 */
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.239.
// 
#pragma warning disable 1591

namespace Accela.ACA.WSProxy {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PageFlowConfigWebServiceServiceSoapBinding", Namespace="http://service.webservice.accela.com/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LanguageModel))]
    public partial class PageFlowConfigWebServiceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getPageFlowComponentsByCapIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback createPageFlowGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPageFlowGroupByCapIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback editePageFlowGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPageFlowGroupNameListOperationCompleted;
        
        private System.Threading.SendOrPostCallback getComponentDefListOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPageFlowGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback deletePageFlowGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback getAllPageFlowGroupOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PageFlowConfigWebServiceService() {
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getPageFlowComponentsByCapIDCompletedEventHandler getPageFlowComponentsByCapIDCompleted;
        
        /// <remarks/>
        public event createPageFlowGroupCompletedEventHandler createPageFlowGroupCompleted;
        
        /// <remarks/>
        public event getPageFlowGroupByCapIDCompletedEventHandler getPageFlowGroupByCapIDCompleted;
        
        /// <remarks/>
        public event editePageFlowGroupCompletedEventHandler editePageFlowGroupCompleted;
        
        /// <remarks/>
        public event getPageFlowGroupNameListCompletedEventHandler getPageFlowGroupNameListCompleted;
        
        /// <remarks/>
        public event getComponentDefListCompletedEventHandler getComponentDefListCompleted;
        
        /// <remarks/>
        public event getPageFlowGroupCompletedEventHandler getPageFlowGroupCompleted;
        
        /// <remarks/>
        public event deletePageFlowGroupCompletedEventHandler deletePageFlowGroupCompleted;
        
        /// <remarks/>
        public event getAllPageFlowGroupCompletedEventHandler getAllPageFlowGroupCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.webservice.accela.com/", ResponseNamespace="http://service.webservice.accela.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PageFlowComponentModel[] getPageFlowComponentsByCapID([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] CapIDModel arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg1) {
            object[] results = this.Invoke("getPageFlowComponentsByCapID", new object[] {
                        arg0,
                        arg1});
            return ((PageFlowComponentModel[])(results[0]));
        }
        
        /// <remarks/>
        public void getPageFlowComponentsByCapIDAsync(CapIDModel arg0, string arg1) {
            this.getPageFlowComponentsByCapIDAsync(arg0, arg1, null);
        }
        
        /// <remarks/>
        public void getPageFlowComponentsByCapIDAsync(CapIDModel arg0, string arg1, object userState) {
            if ((this.getPageFlowComponentsByCapIDOperationCompleted == null)) {
                this.getPageFlowComponentsByCapIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPageFlowComponentsByCapIDOperationCompleted);
            }
            this.InvokeAsync("getPageFlowComponentsByCapID", new object[] {
                        arg0,
                        arg1}, this.getPageFlowComponentsByCapIDOperationCompleted, userState);
        }
        
        private void OngetPageFlowComponentsByCapIDOperationCompleted(object arg) {
            if ((this.getPageFlowComponentsByCapIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPageFlowComponentsByCapIDCompleted(this, new getPageFlowComponentsByCapIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.webservice.accela.com/", ResponseNamespace="http://service.webservice.accela.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void createPageFlowGroup([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] PageFlowGroupModel arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg1, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg2) {
            this.Invoke("createPageFlowGroup", new object[] {
                        arg0,
                        arg1,
                        arg2});
        }
        
        /// <remarks/>
        public void createPageFlowGroupAsync(PageFlowGroupModel arg0, string arg1, string arg2) {
            this.createPageFlowGroupAsync(arg0, arg1, arg2, null);
        }
        
        /// <remarks/>
        public void createPageFlowGroupAsync(PageFlowGroupModel arg0, string arg1, string arg2, object userState) {
            if ((this.createPageFlowGroupOperationCompleted == null)) {
                this.createPageFlowGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreatePageFlowGroupOperationCompleted);
            }
            this.InvokeAsync("createPageFlowGroup", new object[] {
                        arg0,
                        arg1,
                        arg2}, this.createPageFlowGroupOperationCompleted, userState);
        }
        
        private void OncreatePageFlowGroupOperationCompleted(object arg) {
            if ((this.createPageFlowGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.createPageFlowGroupCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.webservice.accela.com/", ResponseNamespace="http://service.webservice.accela.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PageFlowGroupModel getPageFlowGroupByCapID([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] CapIDModel arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg1) {
            object[] results = this.Invoke("getPageFlowGroupByCapID", new object[] {
                        arg0,
                        arg1});
            return ((PageFlowGroupModel)(results[0]));
        }
        
        /// <remarks/>
        public void getPageFlowGroupByCapIDAsync(CapIDModel arg0, string arg1) {
            this.getPageFlowGroupByCapIDAsync(arg0, arg1, null);
        }
        
        /// <remarks/>
        public void getPageFlowGroupByCapIDAsync(CapIDModel arg0, string arg1, object userState) {
            if ((this.getPageFlowGroupByCapIDOperationCompleted == null)) {
                this.getPageFlowGroupByCapIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPageFlowGroupByCapIDOperationCompleted);
            }
            this.InvokeAsync("getPageFlowGroupByCapID", new object[] {
                        arg0,
                        arg1}, this.getPageFlowGroupByCapIDOperationCompleted, userState);
        }
        
        private void OngetPageFlowGroupByCapIDOperationCompleted(object arg) {
            if ((this.getPageFlowGroupByCapIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPageFlowGroupByCapIDCompleted(this, new getPageFlowGroupByCapIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.webservice.accela.com/", ResponseNamespace="http://service.webservice.accela.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void editePageFlowGroup([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] PageFlowGroupModel arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg1, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg2) {
            this.Invoke("editePageFlowGroup", new object[] {
                        arg0,
                        arg1,
                        arg2});
        }
        
        /// <remarks/>
        public void editePageFlowGroupAsync(PageFlowGroupModel arg0, string arg1, string arg2) {
            this.editePageFlowGroupAsync(arg0, arg1, arg2, null);
        }
        
        /// <remarks/>
        public void editePageFlowGroupAsync(PageFlowGroupModel arg0, string arg1, string arg2, object userState) {
            if ((this.editePageFlowGroupOperationCompleted == null)) {
                this.editePageFlowGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OneditePageFlowGroupOperationCompleted);
            }
            this.InvokeAsync("editePageFlowGroup", new object[] {
                        arg0,
                        arg1,
                        arg2}, this.editePageFlowGroupOperationCompleted, userState);
        }
        
        private void OneditePageFlowGroupOperationCompleted(object arg) {
            if ((this.editePageFlowGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.editePageFlowGroupCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.webservice.accela.com/", ResponseNamespace="http://service.webservice.accela.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] getPageFlowGroupNameList([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg1) {
            object[] results = this.Invoke("getPageFlowGroupNameList", new object[] {
                        arg0,
                        arg1});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void getPageFlowGroupNameListAsync(string arg0, string arg1) {
            this.getPageFlowGroupNameListAsync(arg0, arg1, null);
        }
        
        /// <remarks/>
        public void getPageFlowGroupNameListAsync(string arg0, string arg1, object userState) {
            if ((this.getPageFlowGroupNameListOperationCompleted == null)) {
                this.getPageFlowGroupNameListOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPageFlowGroupNameListOperationCompleted);
            }
            this.InvokeAsync("getPageFlowGroupNameList", new object[] {
                        arg0,
                        arg1}, this.getPageFlowGroupNameListOperationCompleted, userState);
        }
        
        private void OngetPageFlowGroupNameListOperationCompleted(object arg) {
            if ((this.getPageFlowGroupNameListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPageFlowGroupNameListCompleted(this, new getPageFlowGroupNameListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.webservice.accela.com/", ResponseNamespace="http://service.webservice.accela.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ComponentModel[] getComponentDefList([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg1) {
            object[] results = this.Invoke("getComponentDefList", new object[] {
                        arg0,
                        arg1});
            return ((ComponentModel[])(results[0]));
        }
        
        /// <remarks/>
        public void getComponentDefListAsync(string arg0, string arg1) {
            this.getComponentDefListAsync(arg0, arg1, null);
        }
        
        /// <remarks/>
        public void getComponentDefListAsync(string arg0, string arg1, object userState) {
            if ((this.getComponentDefListOperationCompleted == null)) {
                this.getComponentDefListOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetComponentDefListOperationCompleted);
            }
            this.InvokeAsync("getComponentDefList", new object[] {
                        arg0,
                        arg1}, this.getComponentDefListOperationCompleted, userState);
        }
        
        private void OngetComponentDefListOperationCompleted(object arg) {
            if ((this.getComponentDefListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getComponentDefListCompleted(this, new getComponentDefListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.webservice.accela.com/", ResponseNamespace="http://service.webservice.accela.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PageFlowGroupModel getPageFlowGroup([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg1, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg2, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg3) {
            object[] results = this.Invoke("getPageFlowGroup", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3});
            return ((PageFlowGroupModel)(results[0]));
        }
        
        /// <remarks/>
        public void getPageFlowGroupAsync(string arg0, string arg1, string arg2, string arg3) {
            this.getPageFlowGroupAsync(arg0, arg1, arg2, arg3, null);
        }
        
        /// <remarks/>
        public void getPageFlowGroupAsync(string arg0, string arg1, string arg2, string arg3, object userState) {
            if ((this.getPageFlowGroupOperationCompleted == null)) {
                this.getPageFlowGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPageFlowGroupOperationCompleted);
            }
            this.InvokeAsync("getPageFlowGroup", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3}, this.getPageFlowGroupOperationCompleted, userState);
        }
        
        private void OngetPageFlowGroupOperationCompleted(object arg) {
            if ((this.getPageFlowGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPageFlowGroupCompleted(this, new getPageFlowGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.webservice.accela.com/", ResponseNamespace="http://service.webservice.accela.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void deletePageFlowGroup([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg1, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg2, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg3) {
            this.Invoke("deletePageFlowGroup", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3});
        }
        
        /// <remarks/>
        public void deletePageFlowGroupAsync(string arg0, string arg1, string arg2, string arg3) {
            this.deletePageFlowGroupAsync(arg0, arg1, arg2, arg3, null);
        }
        
        /// <remarks/>
        public void deletePageFlowGroupAsync(string arg0, string arg1, string arg2, string arg3, object userState) {
            if ((this.deletePageFlowGroupOperationCompleted == null)) {
                this.deletePageFlowGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeletePageFlowGroupOperationCompleted);
            }
            this.InvokeAsync("deletePageFlowGroup", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3}, this.deletePageFlowGroupOperationCompleted, userState);
        }
        
        private void OndeletePageFlowGroupOperationCompleted(object arg) {
            if ((this.deletePageFlowGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deletePageFlowGroupCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.webservice.accela.com/", ResponseNamespace="http://service.webservice.accela.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PageFlowGroupModel[] getAllPageFlowGroup([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg1) {
            object[] results = this.Invoke("getAllPageFlowGroup", new object[] {
                        arg0,
                        arg1});
            return ((PageFlowGroupModel[])(results[0]));
        }
        
        /// <remarks/>
        public void getAllPageFlowGroupAsync(string arg0, string arg1) {
            this.getAllPageFlowGroupAsync(arg0, arg1, null);
        }
        
        /// <remarks/>
        public void getAllPageFlowGroupAsync(string arg0, string arg1, object userState) {
            if ((this.getAllPageFlowGroupOperationCompleted == null)) {
                this.getAllPageFlowGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAllPageFlowGroupOperationCompleted);
            }
            this.InvokeAsync("getAllPageFlowGroup", new object[] {
                        arg0,
                        arg1}, this.getAllPageFlowGroupOperationCompleted, userState);
        }
        
        private void OngetAllPageFlowGroupOperationCompleted(object arg) {
            if ((this.getAllPageFlowGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAllPageFlowGroupCompleted(this, new getAllPageFlowGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getPageFlowComponentsByCapIDCompletedEventHandler(object sender, getPageFlowComponentsByCapIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPageFlowComponentsByCapIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPageFlowComponentsByCapIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PageFlowComponentModel[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PageFlowComponentModel[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void createPageFlowGroupCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getPageFlowGroupByCapIDCompletedEventHandler(object sender, getPageFlowGroupByCapIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPageFlowGroupByCapIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPageFlowGroupByCapIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PageFlowGroupModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PageFlowGroupModel)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void editePageFlowGroupCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getPageFlowGroupNameListCompletedEventHandler(object sender, getPageFlowGroupNameListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPageFlowGroupNameListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPageFlowGroupNameListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getComponentDefListCompletedEventHandler(object sender, getComponentDefListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getComponentDefListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getComponentDefListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ComponentModel[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ComponentModel[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getPageFlowGroupCompletedEventHandler(object sender, getPageFlowGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPageFlowGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPageFlowGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PageFlowGroupModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PageFlowGroupModel)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void deletePageFlowGroupCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getAllPageFlowGroupCompletedEventHandler(object sender, getAllPageFlowGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getAllPageFlowGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAllPageFlowGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PageFlowGroupModel[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PageFlowGroupModel[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591